#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_IBM_ASM)		+= ibmasm/
obj-$(CONFIG_HDPU_FEATURES)	+= hdpuftrs/
obj-$(CONFIG_ATMEL_PWM)		+= atmel_pwm.o
obj-$(CONFIG_ATMEL_SSC)		+= atmel-ssc.o
obj-$(CONFIG_ATMEL_TCLIB)	+= atmel_tclib.o
obj-$(CONFIG_ICS932S401)	+= ics932s401.o
obj-$(CONFIG_LKDTM)		+= lkdtm.o
obj-$(CONFIG_TIFM_CORE)       	+= tifm_core.o
obj-$(CONFIG_TIFM_7XX1)       	+= tifm_7xx1.o
obj-$(CONFIG_PHANTOM)		+= phantom.o
obj-$(CONFIG_ANDROID_PMEM)	+= pmem.o
obj-$(CONFIG_SGI_IOC4)		+= ioc4.o
obj-$(CONFIG_ENCLOSURE_SERVICES) += enclosure.o
obj-$(CONFIG_KERNEL_DEBUGGER_CORE)	+= kernel_debugger.o
obj-$(CONFIG_KGDB_TESTS)	+= kgdbts.o
obj-$(CONFIG_SGI_XP)		+= sgi-xp/
obj-$(CONFIG_SGI_GRU)		+= sgi-gru/
obj-$(CONFIG_HP_ILO)		+= hpilo.o
obj-$(CONFIG_ISL29003)		+= isl29003.o
obj-$(CONFIG_EP93XX_PWM)	+= ep93xx_pwm.o
obj-$(CONFIG_UID_STAT)		+= uid_stat.o
obj-$(CONFIG_C2PORT)		+= c2port/
obj-y				+= eeprom/
obj-y				+= cb710/
obj-$(CONFIG_LBEE9QMB_RFKILL)	+= lbee9qmb-rfkill.o
obj-$(CONFIG_WL127X_RFKILL)	+= wl127x-rfkill.o
obj-$(CONFIG_APANIC)		+= apanic.o
obj-$(CONFIG_APANIC_MMC)	+= apanic_handle_mmc.o apanic_report_block.o
obj-$(CONFIG_MOT_FEAT_TS27010MUX)	+= ts27010mux/
obj-$(CONFIG_SENSORS_KXTF9)	+= kxtf9.o
obj-$(CONFIG_VIB_GPIO)		+= vib-gpio.o
obj-$(CONFIG_VIB_PWM)		+= vib-pwm.o
obj-$(CONFIG_MOT_SEC_DRIVER)	+= sec/
obj-$(CONFIG_MOT_TCMD_DRIVER)	+= tcmd_driver.o
obj-$(CONFIG_MDM_CTRL)		+= mdm_ctrl.o
obj-y                           += radio_ctrl/
obj-$(CONFIG_SENSORS_L3G4200D)	+= l3g4200d.o
obj-$(CONFIG_TTY_SPI_SLAVE_MDM6600)   += spi-tty/
obj-$(CONFIG_MOT_VNI_DRIVER) += vni/
obj-$(CONFIG_MISC_NVODMCAM)     += nvodmcam.o
