ifeq ($(USE_MMRIL),true)
  ccflags-y += -DMOT_TURN_ON_LTE
endif

obj-$(CONFIG_TEGRA_ODM_HARMONY)		+= harmony/
obj-$(CONFIG_TEGRA_ODM_VENTANA)		+= ventana/
obj-$(CONFIG_TEGRA_ODM_WHISTLER)	+= whistler/

obj-$(CONFIG_TEGRA_ODM_OLYMPUS) += olympus/
obj-$(CONFIG_TEGRA_ODM_ETNA) += etna/
obj-$(CONFIG_TEGRA_ODM_DAYTONA) += daytona/
obj-$(CONFIG_TEGRA_ODM_SUNFIRE) += sunfire/
